/**
 * prisma/seed-ukpsc-quiz-expansion.ts
 *
 * Idempotent seed script to expand the UKPSC Quiz Content:
 * Adds 10 new topics (2 per existing subject) and 50 new MCQs (5 per topic).
 *
 * Rules:
 *  - Use stable static IDs (upsert) to be safe to re-run
 *  - No deleteMany
 *  - High-quality, real questions relevant to UKPSC syllabus
 */

import { PrismaClient, CorrectOption, Difficulty } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";
import * as dotenv from "dotenv";

interface QuestionInput {
  id: string;
  topicId: string;
  text: string;
  textHi: string;
  optionA: string;
  optionAHi: string;
  optionB: string;
  optionBHi: string;
  optionC: string;
  optionCHi: string;
  optionD: string;
  optionDHi: string;
  correctOption: CorrectOption;
  explanation: string;
  explanationHi: string;
  difficulty: Difficulty;
  isPYQ: boolean;
  pyqYear?: number | null;
}

dotenv.config({ path: ".env.local" });

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  throw new Error("DATABASE_URL is not set in .env.local");
}

const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });


// ─── Subject IDs from seed-ukpsc-mvp.js ─────────────────────────────────────
const SUB_UTGK = "subject-uuid-static-utgk-1111";
const SUB_GEO = "subject-uuid-static-geo-2222";
const SUB_POL = "subject-uuid-static-pol-3333";
const SUB_CA = "subject-uuid-static-ca-4444";
const SUB_HINDI = "subject-uuid-static-hindi-5555";

// ─── 1. New Topics ──────────────────────────────────────────────────────────
const newTopics = [
  // --- Uttarakhand Specific Knowledge ---
  {
    id: "topic-uuid-static-utgk-t2",
    subjectId: SUB_UTGK,
    title: "Geography and Environment of Uttarakhand",
    titleHi: "उत्तराखंड का भूगोल एवं पर्यावरण",
    content: "Uttarakhand is a mountainous state characterized by Himalayan peaks, glaciers, rivers, and rich biodiversity. Notable geographical features include Nanda Devi peak, Gangotri and Satopanth glaciers, and protected areas like the Valley of Flowers National Park.",
    contentHi: "उत्तराखंड एक पहाड़ी राज्य है जो हिमालय की चोटियों, ग्लेशियरों, नदियों और समृद्ध जैव विविधता से परिपूर्ण है। उल्लेखनीय भौगोलिक विशेषताओं में नंदा देवी चोटी, गंगोत्री और सतोपंथ ग्लेशियर, और फूलों की घाटी राष्ट्रीय उद्यान जैसे संरक्षित क्षेत्र शामिल हैं।",
    estimatedMinutes: 15,
    orderIndex: 2,
  },
  {
    id: "topic-uuid-static-utgk-t3",
    subjectId: SUB_UTGK,
    title: "Polity and Districts of Uttarakhand",
    titleHi: "उत्तराखंड की राजव्यवस्था एवं जिले",
    content: "Uttarakhand was carved out of Uttar Pradesh on November 9, 2000. It has a unicameral legislature with 70 Assembly seats, 5 Lok Sabha seats, and 3 Rajya Sabha seats. The state is divided into 13 districts with Nainital hosting the High Court and Gairsain acting as the summer capital.",
    contentHi: "उत्तराखंड का गठन 9 नवंबर 2000 को उत्तर प्रदेश से अलग करके किया गया था। यहाँ एकसदनीय विधायिका है जिसमें 70 विधानसभा सीटें, 5 लोकसभा सीटें और 3 राज्यसभा सीटें हैं। राज्य को 13 जिलों में विभाजित किया गया है, नैनीताल में उच्च न्यायालय है और गैरसैंण ग्रीष्मकालीन राजधानी है।",
    estimatedMinutes: 15,
    orderIndex: 3,
  },

  // --- Geography ---
  {
    id: "topic-uuid-static-geo-t2",
    subjectId: SUB_GEO,
    title: "Indian Drainage System and Rivers",
    titleHi: "भारत का अपवाह तंत्र एवं नदियाँ",
    content: "India's drainage system is divided into Himalayan rivers (perennial, like Ganga, Brahmaputra, and Indus) and Peninsular rivers (seasonal, like Godavari, Krishna, Narmada, and Kaveri). Confluences (Prayags) hold high cultural and ecological significance.",
    contentHi: "भारत के अपवाह तंत्र को हिमालयी नदियों (सदाबहार, जैसे गंगा, ब्रह्मपुत्र और सिंधु) और प्रायद्वीपीय नदियों (मौसमी, जैसे गोदावरी, कृष्णा, नर्मदा और कावेरी) में विभाजित किया गया है। पंचप्रयागों का सांस्कृतिक और पारिस्थितिक महत्व अत्यधिक है।",
    estimatedMinutes: 15,
    orderIndex: 2,
  },
  {
    id: "topic-uuid-static-geo-t3",
    subjectId: SUB_GEO,
    title: "Soil and Vegetation of India",
    titleHi: "भारत की मृदा एवं वनस्पति",
    content: "Major soil types in India include Alluvial (most widespread), Black (Regur, ideal for cotton), Red, and Laterite. The vegetation ranges from Tropical Evergreen in heavy rainfall zones to Tropical Deciduous (most common) and Mangrove forests in coastal deltas.",
    contentHi: "भारत में प्रमुख मृदा प्रकारों में जलोढ़ (सबसे व्यापक), काली (रेगुर, कपास के लिए आदर्श), लाल और लेटेराइट शामिल हैं। वनस्पति में भारी वर्षा वाले क्षेत्रों में उष्णकटिबंधीय सदाबहार से लेकर उष्णकटिबंधीय पर्णपाती (सबसे आम) और तटीय डेल्टा में मैंग्रोव वन शामिल हैं।",
    estimatedMinutes: 15,
    orderIndex: 3,
  },

  // --- Indian Polity ---
  {
    id: "topic-uuid-static-pol-t2",
    subjectId: SUB_POL,
    title: "Directive Principles and Fundamental Duties",
    titleHi: "राज्य के नीति निदेशक तत्व और मौलिक कर्तव्य",
    content: "Directive Principles of State Policy (Part IV, Articles 36-51) are non-justiciable guidelines for establishing a welfare state, inspired by Ireland. Fundamental Duties (Part IVA, Article 51A) were added by the 42nd Amendment in 1976 on the Swaran Singh Committee's recommendation.",
    contentHi: "राज्य के नीति निदेशक तत्व (भाग IV, अनुच्छेद 36-51) कल्याणकारी राज्य की स्थापना के लिए गैर-वादयोग्य मार्गदर्शिका हैं, जो आयरलैंड से प्रेरित हैं। मौलिक कर्तव्य (भाग IVA, अनुच्छेद 51A) को 1976 में स्वर्ण सिंह समिति की सिफारिश पर 42वें संशोधन द्वारा जोड़ा गया था।",
    estimatedMinutes: 15,
    orderIndex: 2,
  },
  {
    id: "topic-uuid-static-pol-t3",
    subjectId: SUB_POL,
    title: "Union Parliament and State Legislature",
    titleHi: "संघीय संसद और राज्य विधानमंडल",
    content: "The Union Parliament consists of the President, Rajya Sabha (Upper House, permanent), and Lok Sabha (Lower House, 5-year term). State Legislatures can be bicameral or unicameral. Key concepts include money bills, sessions, and legislative procedures.",
    contentHi: "संघीय संसद में राष्ट्रपति, राज्यसभा (उच्च सदन, स्थायी) और लोकसभा (निम्न सदन, 5 वर्ष का कार्यकाल) शामिल हैं। राज्य विधानमंडल द्विसदनीय या एकसदनीय हो सकते हैं। मुख्य अवधारणाओं में धन विधेयक, सत्र और विधायी प्रक्रियाएं शामिल हैं।",
    estimatedMinutes: 15,
    orderIndex: 3,
  },

  // --- Current Affairs ---
  {
    id: "topic-uuid-static-ca-t2",
    subjectId: SUB_CA,
    title: "Uttarakhand Current Affairs",
    titleHi: "उत्तराखंड समसामयिकी",
    content: "Focuses on recent events in Uttarakhand, including the passage of the Uniform Civil Code (UCC) Bill in 2024, the Silkyara tunnel rescue operations, infrastructure projects like Lakhwar, and environmental initiatives.",
    contentHi: "उत्तराखंड की हालिया घटनाओं पर ध्यान केंद्रित करता है, जिसमें 2024 में समान नागरिक संहिता (UCC) विधेयक का पारित होना, सिल्क्यारा सुरंग बचाव अभियान, लखवाड़ जैसी बुनियादी ढांचा परियोजनाएं और पर्यावरणीय पहल शामिल हैं।",
    estimatedMinutes: 15,
    orderIndex: 2,
  },
  {
    id: "topic-uuid-static-ca-t3",
    subjectId: SUB_CA,
    title: "Central Government Schemes",
    titleHi: "केंद्र सरकार की योजनाएं",
    content: "Covers major social sector schemes launched by the Government of India, including PM Jan Dhan Yojana (financial inclusion), PM Ujjwala Yojana (LPG connections), Ayushman Bharat PM-JAY (healthcare), PM Vishwakarma (artisans), and Jal Jeevan Mission.",
    contentHi: "भारत सरकार द्वारा शुरू की गई प्रमुख सामाजिक क्षेत्र की योजनाओं को कवर करता है, जिसमें पीएम जन धन योजना (वित्तीय समावेशन), पीएम उज्ज्वला योजना (एलपीजी कनेक्शन), आयुष्मान भारत पीएम-जेएवाई (स्वास्थ्य सेवा), पीएम विश्वकर्मा (कारीगर), और जल जीवन मिशन शामिल हैं।",
    estimatedMinutes: 15,
    orderIndex: 3,
  },

  // --- Basic Hindi ---
  {
    id: "topic-uuid-static-hindi-t2",
    subjectId: SUB_HINDI,
    title: "Hindi Grammar: Sandhi and Samas",
    titleHi: "हिन्दी व्याकरण: संधि और समास",
    content: "Sandhi refers to the phonetic joining of two words (Swar, Vyanjan, Visarg Sandhi). Samas is the compounding of words to form a concise term (types include Avyayibhav, Tatpurush, Dwandwa, Bahuvrihi, Dvigu, and Karmadharaya).",
    contentHi: "संधि दो निकटवर्ती वर्णों के परस्पर मेल से होने वाले परिवर्तन को कहते हैं (स्वर, व्यंजन, विसर्ग संधि)। समास दो या दो से अधिक शब्दों को मिलाकर एक संक्षिप्त शब्द बनाने की प्रक्रिया है (अव्ययीभाव, तत्पुरुष, द्वंद्व, बहुव्रीहि, द्विगु और कर्मधारय)।",
    estimatedMinutes: 15,
    orderIndex: 2,
  },
  {
    id: "topic-uuid-static-hindi-t3",
    subjectId: SUB_HINDI,
    title: "Hindi Grammar: Muhavare and Lokoktiyan",
    titleHi: "हिन्दी व्याकरण: मुहावरे और लोकोक्तियाँ",
    content: "Muhavare (idioms) are phrases that convey a figurative meaning rather than a literal one. Lokoktiyan (proverbs) are complete sentences expressing traditional wisdom or community experience.",
    contentHi: "मुहावरे ऐसे वाक्यांश होते हैं जो सामान्य अर्थ न देकर विशेष अर्थ प्रकट करते हैं। लोकोक्तियाँ (कहावतें) वे पूर्ण वाक्य होते हैं जो किसी पारंपरिक ज्ञान या लोक अनुभव को व्यक्त करते हैं।",
    estimatedMinutes: 15,
    orderIndex: 3,
  },
];

// ─── 2. New Questions (5 per topic) ─────────────────────────────────────────
const newQuestions: QuestionInput[] = [
  // === Uttarakhand Geography & Environment (topic-uuid-static-utgk-t2) ===
  {
    id: "q-uuid-utgk-t2-1",
    topicId: "topic-uuid-static-utgk-t2",
    text: "Which is the highest mountain peak situated entirely within Uttarakhand?",
    textHi: "पूर्ण रूप से उत्तराखंड में स्थित सबसे ऊँची पर्वत चोटी कौन सी है?",
    optionA: "Nanda Devi", optionAHi: "नंदा देवी",
    optionB: "Kamet", optionBHi: "कामेत",
    optionC: "Trisul", optionCHi: "त्रिशूल",
    optionD: "Chaukhamba", optionDHi: "चौखंबा",
    correctOption: "A",
    explanation: "Nanda Devi is the highest mountain peak in Uttarakhand, standing at 7,816 meters above sea level.",
    explanationHi: "नंदा देवी उत्तराखंड की सबसे ऊँची चोटी है, जो समुद्र तल से 7,816 मीटर की ऊँचाई पर स्थित है।",
    difficulty: "EASY",
    isPYQ: true,
    pyqYear: 2021,
  },
  {
    id: "q-uuid-utgk-t2-2",
    topicId: "topic-uuid-static-utgk-t2",
    text: "In which district of Uttarakhand is the Valley of Flowers National Park located?",
    textHi: "उत्तराखंड के किस जिले में फूलों की घाटी राष्ट्रीय उद्यान स्थित है?",
    optionA: "Chamoli", optionAHi: "चमोली",
    optionB: "Pithoragarh", optionBHi: "पिथौरागढ़",
    optionC: "Uttarkashi", optionCHi: "उत्तरकाशी",
    optionD: "Rudraprayag", optionDHi: "रुद्रप्रयाग",
    correctOption: "A",
    explanation: "The Valley of Flowers National Park is located in Chamoli district and is renowned for its diverse alpine flora. It is a UNESCO World Heritage Site.",
    explanationHi: "फूलों की घाटी राष्ट्रीय उद्यान चमोली जिले में स्थित है और यह अपने विविध अल्पाइन फूलों के लिए प्रसिद्ध है। यह यूनेस्को की विश्व धरोहर स्थल है।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-utgk-t2-3",
    topicId: "topic-uuid-static-utgk-t2",
    text: "Which glacier is the primary source of the Alaknanda River?",
    textHi: "कौन सा ग्लेशियर अलकनंदा नदी का प्राथमिक स्रोत है?",
    optionA: "Satopanth Glacier", optionAHi: "सतोपंथ ग्लेशियर",
    optionB: "Gangotri Glacier", optionBHi: "गंगोत्री ग्लेशियर",
    optionC: "Milam Glacier", optionCHi: "मिलम ग्लेशियर",
    optionD: "Pindari Glacier", optionDHi: "पिंडारी ग्लेशियर",
    correctOption: "A",
    explanation: "The Alaknanda River originates from the Satopanth Glacier near Badrinath in Chamoli district.",
    explanationHi: "अलकनंदा नदी चमोली जिले में बद्रीनाथ के पास सतोपंथ ग्लेशियर से निकलती है।",
    difficulty: "MEDIUM",
    isPYQ: true,
    pyqYear: 2018,
  },
  {
    id: "q-uuid-utgk-t2-4",
    topicId: "topic-uuid-static-utgk-t2",
    text: "The Tehri Dam is constructed on which of the following rivers?",
    textHi: "टिहरी बाँध का निर्माण निम्नलिखित में से किस नदी पर किया गया है?",
    optionA: "Bhagirathi", optionAHi: "भागीरथी",
    optionB: "Alaknanda", optionBHi: "अलकनंदा",
    optionC: "Yamuna", optionCHi: "यमुना",
    optionD: "Mandakini", optionDHi: "मंदारकिनी",
    correctOption: "A",
    explanation: "The Tehri Dam is a multi-purpose rock and earth-fill embankment dam on the Bhagirathi River near Tehri in Uttarakhand.",
    explanationHi: "टिहरी बाँध उत्तराखंड में टिहरी के पास भागीरथी नदी पर बना एक बहुउद्देशीय चट्टान और मिट्टी-भराव वाला तटबंध बाँध है।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-utgk-t2-5",
    topicId: "topic-uuid-static-utgk-t2",
    text: "Which of the following districts has the smallest geographical area in Uttarakhand?",
    textHi: "उत्तराखंड में निम्नलिखित में से किस जिले का भौगोलिक क्षेत्रफल सबसे कम है?",
    optionA: "Champawat", optionAHi: "चंपावत",
    optionB: "Rudraprayag", optionBHi: "रुद्रप्रयाग",
    optionC: "Bageshwar", optionCHi: "बागेश्वर",
    optionD: "Haridwar", optionDHi: "हरिद्वार",
    correctOption: "A",
    explanation: "Champawat is the smallest district of Uttarakhand by geographical area, covering approximately 1,766 square kilometers.",
    explanationHi: "चंपावत भौगोलिक क्षेत्रफल के हिसाब से उत्तराखंड का सबसे छोटा जिला है, जिसका क्षेत्रफल लगभग 1,766 वर्ग किलोमीटर है।",
    difficulty: "MEDIUM",
    isPYQ: true,
    pyqYear: 2016,
  },

  // === Uttarakhand Polity & Districts (topic-uuid-static-utgk-t3) ===
  {
    id: "q-uuid-utgk-t3-1",
    topicId: "topic-uuid-static-utgk-t3",
    text: "Who was the first Chief Minister of Uttarakhand?",
    textHi: "उत्तराखंड के प्रथम मुख्यमंत्री कौन थे?",
    optionA: "Nityanand Swami", optionAHi: "नित्यानंद स्वामी",
    optionB: "Bhagat Singh Koshyari", optionBHi: "भगत सिंह कोश्यारी",
    optionC: "N. D. Tiwari", optionCHi: "एन. डी. तिवारी",
    optionD: "B. C. Khanduri", optionDHi: "बी. सी. खंडूरी",
    correctOption: "A",
    explanation: "Nityanand Swami was the first Chief Minister of Uttarakhand, taking office on November 9, 2000, when the state was formed.",
    explanationHi: "नित्यानंद स्वामी उत्तराखंड के पहले मुख्यमंत्री थे, जिन्होंने 9 नवंबर 2000 को राज्य गठन के समय पदभार संभाला था।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-utgk-t3-2",
    topicId: "topic-uuid-static-utgk-t3",
    text: "How many Lok Sabha seats are allocated to the state of Uttarakhand?",
    textHi: "उत्तराखंड राज्य के लिए कितनी लोकसभा सीटें आवंटित हैं?",
    optionA: "5", optionAHi: "5",
    optionB: "3", optionBHi: "3",
    optionC: "70", optionCHi: "70",
    optionD: "13", optionDHi: "13",
    correctOption: "A",
    explanation: "Uttarakhand has 5 Lok Sabha constituencies: Tehri Garhwal, Garhwal, Almora (SC), Nainital-Udhamsingh Nagar, and Haridwar.",
    explanationHi: "उत्तराखंड में 5 लोकसभा निर्वाचन क्षेत्र हैं: टिहरी गढ़वाल, गढ़वाल, अल्मोड़ा (SC), नैनीताल-ऊधमसिंह नगर और हरिद्वार।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-utgk-t3-3",
    topicId: "topic-uuid-static-utgk-t3",
    text: "Where is the High Court of Uttarakhand officially located?",
    textHi: "उत्तराखंड का उच्च न्यायालय आधिकारिक तौर पर कहाँ स्थित है?",
    optionA: "Nainital", optionAHi: "नैनीताल",
    optionB: "Dehradun", optionBHi: "देहरादून",
    optionC: "Haldwani", optionCHi: "हल्द्वानी",
    optionD: "Gairsain", optionDHi: "गैरसैंण",
    correctOption: "A",
    explanation: "The High Court of Uttarakhand is located in Nainital, housed in a historic building built during the British era.",
    explanationHi: "उत्तराखंड का उच्च न्यायालय नैनीताल में स्थित है, जो ब्रिटिश काल में बनी एक ऐतिहासिक इमारत में स्थित है।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-utgk-t3-4",
    topicId: "topic-uuid-static-utgk-t3",
    text: "Which town was declared as the official Summer Capital of Uttarakhand in June 2020?",
    textHi: "जून 2020 में किस शहर को उत्तराखंड की आधिकारिक ग्रीष्मकालीन राजधानी घोषित किया गया था?",
    optionA: "Gairsain", optionAHi: "गैरसैंण",
    optionB: "Dehradun", optionBHi: "देहरादून",
    optionC: "Mussoorie", optionCHi: "मसूरी",
    optionD: "Srinagar", optionDHi: "श्रीनगर",
    correctOption: "A",
    explanation: "Gairsain (specifically Bhararisain) was officially declared as the Summer Capital of Uttarakhand on June 8, 2020.",
    explanationHi: "गैरसैंण (विशेष रूप से भरारीसैंण) को आधिकारिक तौर पर 8 जून 2020 को उत्तराखंड की ग्रीष्मकालीन राजधानी घोषित किया गया था।",
    difficulty: "MEDIUM",
    isPYQ: true,
    pyqYear: 2021,
  },
  {
    id: "q-uuid-utgk-t3-5",
    topicId: "topic-uuid-static-utgk-t3",
    text: "In which year was the name of the state officially changed from Uttaranchal to Uttarakhand?",
    textHi: "किस वर्ष राज्य का नाम आधिकारिक तौर पर उत्तरांचल से बदलकर उत्तराखंड किया गया था?",
    optionA: "2007", optionAHi: "2007",
    optionB: "2000", optionBHi: "2000",
    optionC: "2005", optionCHi: "2005",
    optionD: "2009", optionDHi: "2009",
    correctOption: "A",
    explanation: "The state was renamed from Uttaranchal to Uttarakhand on January 1, 2007, reflecting the historical name of the region.",
    explanationHi: "क्षेत्र के ऐतिहासिक नाम को दर्शाते हुए, 1 जनवरी 2007 को राज्य का नाम उत्तरांचल से बदलकर उत्तराखंड कर दिया गया था।",
    difficulty: "EASY",
    isPYQ: true,
    pyqYear: 2012,
  },

  // === Indian Drainage System (topic-uuid-static-geo-t2) ===
  {
    id: "q-uuid-geo-t2-1",
    topicId: "topic-uuid-static-geo-t2",
    text: "Which is the longest river flowing entirely within India?",
    textHi: "पूर्ण रूप से भारत के भीतर बहने वाली सबसे लंबी नदी कौन सी है?",
    optionA: "Ganga", optionAHi: "गंगा",
    optionB: "Godavari", optionBHi: "गोदावरी",
    optionC: "Brahmaputra", optionCHi: "ब्रह्मपुत्र",
    optionD: "Indus", optionDHi: "सिंधु",
    correctOption: "A",
    explanation: "The Ganga is the longest river in India, covering a distance of 2,525 km within the country.",
    explanationHi: "गंगा भारत की सबसे लंबी नदी है, जो देश के भीतर 2,525 किमी की दूरी तय करती है।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-geo-t2-2",
    topicId: "topic-uuid-static-geo-t2",
    text: "Which of the following rivers is commonly referred to as the 'Dakshin Ganga'?",
    textHi: "निम्नलिखित में से किस नदी को आमतौर पर 'दक्षिण गंगा' कहा जाता है?",
    optionA: "Godavari", optionAHi: "गोदावरी",
    optionB: "Krishna", optionBHi: "कृष्णा",
    optionC: "Kaveri", optionCHi: "कावेरी",
    optionD: "Mahanadi", optionDHi: "महानदी",
    correctOption: "A",
    explanation: "Godavari is known as Dakshin Ganga (or Vridha Ganga) because of its large size and geographical extent in the south.",
    explanationHi: "गोदावरी को दक्षिण भारत में उसके बड़े आकार और भौगोलिक विस्तार के कारण 'दक्षिण गंगा' (या वृद्ध गंगा) के रूप में जाना जाता है।",
    difficulty: "EASY",
    isPYQ: true,
    pyqYear: 2016,
  },
  {
    id: "q-uuid-geo-t2-3",
    topicId: "topic-uuid-static-geo-t2",
    text: "At which confluence do the Alaknanda and Bhagirathi rivers meet to form the Ganga?",
    textHi: "किस प्रयाग (संगम) पर अलकनंदा और भागीरथी नदियाँ मिलकर गंगा का निर्माण करती हैं?",
    optionA: "Devprayag", optionAHi: "देवप्रयाग",
    optionB: "Rudraprayag", optionBHi: "रुद्रप्रयाग",
    optionC: "Karnaprayag", optionCHi: "कर्णप्रयाग",
    optionD: "Vishnuprayag", optionDHi: "विष्णुप्रयाग",
    correctOption: "A",
    explanation: "Devprayag is the final confluence of the Alaknanda and Bhagirathi rivers, from where the river is called the Ganga.",
    explanationHi: "देवप्रयाग अलकनंदा और भागीरथी नदियों का अंतिम संगम है, जहाँ से इस नदी को गंगा कहा जाता है।",
    difficulty: "EASY",
    isPYQ: true,
    pyqYear: 2021,
  },
  {
    id: "q-uuid-geo-t2-4",
    topicId: "topic-uuid-static-geo-t2",
    text: "Which of the following rivers originates from the Amarkantak plateau in Madhya Pradesh?",
    textHi: "निम्नलिखित में से कौन सी नदी मध्य प्रदेश में अमरकंटक पठार से निकलती है?",
    optionA: "Narmada", optionAHi: "नर्मदा",
    optionB: "Godavari", optionBHi: "गोदावरी",
    optionC: "Krishna", optionCHi: "कृष्णा",
    optionD: "Yamuna", optionDHi: "यमुना",
    correctOption: "A",
    explanation: "The Narmada River originates from the Narmada Kund located in the Amarkantak hill plateau in Anuppur district of Madhya Pradesh.",
    explanationHi: "नर्मदा नदी मध्य प्रदेश के अनूपपुर जिले में अमरकंटक पहाड़ी पठार में स्थित नर्मदा कुंड से निकलती है।",
    difficulty: "MEDIUM",
    isPYQ: false,
  },
  {
    id: "q-uuid-geo-t2-5",
    topicId: "topic-uuid-static-geo-t2",
    text: "Which river basin is the largest in geographical area in India?",
    textHi: "भारत में किस नदी का बेसिन भौगोलिक क्षेत्रफल में सबसे बड़ा है?",
    optionA: "Ganga Basin", optionAHi: "गंगा बेसिन",
    optionB: "Godavari Basin", optionBHi: "गोदावरी बेसिन",
    optionC: "Indus Basin", optionCHi: "सिंधु बेसिन",
    optionD: "Krishna Basin", optionDHi: "कृष्णा बेसिन",
    correctOption: "A",
    explanation: "The Ganga River basin is the largest in India, covering approximately 26% of the country's total landmass.",
    explanationHi: "गंगा नदी का बेसिन भारत में सबसे बड़ा है, जो देश के कुल भूभाग का लगभग 26% हिस्सा कवर करता है।",
    difficulty: "EASY",
    isPYQ: false,
  },

  // === Soil and Vegetation of India (topic-uuid-static-geo-t3) ===
  {
    id: "q-uuid-geo-t3-1",
    topicId: "topic-uuid-static-geo-t3",
    text: "Which soil category is the most widespread and productive in India?",
    textHi: "भारत में कौन सी मिट्टी सबसे व्यापक और उपजाऊ है?",
    optionA: "Alluvial Soil", optionAHi: "जलोढ़ मिट्टी",
    optionB: "Black Soil", optionBHi: "काली मिट्टी",
    optionC: "Red Soil", optionCHi: "लाल मिट्टी",
    optionD: "Laterite Soil", optionDHi: "लेटेराइट मिट्टी",
    correctOption: "A",
    explanation: "Alluvial soils are the most widespread, covering about 40% of India's land, and are highly fertile, particularly in the northern plains.",
    explanationHi: "जलोढ़ मिट्टी सबसे व्यापक है, जो भारत की लगभग 40% भूमि को कवर करती है, और विशेष रूप से उत्तरी मैदानों में अत्यधिक उपजाऊ है।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-geo-t3-2",
    topicId: "topic-uuid-static-geo-t3",
    text: "Black soil, famous for cotton cultivation, is also known by which name?",
    textHi: "कपास की खेती के लिए प्रसिद्ध काली मिट्टी को और किस नाम से जाना जाता है?",
    optionA: "Regur Soil", optionAHi: "रेगुर मिट्टी",
    optionB: "Khadar Soil", optionBHi: "खादर मिट्टी",
    optionC: "Bhangar Soil", optionCHi: "भांगर मिट्टी",
    optionD: "Laterite Soil", optionDHi: "लेटेराइट मिट्टी",
    correctOption: "A",
    explanation: "Black soil is commonly known as Regur (or Black Cotton Soil) and is rich in minerals and clay content.",
    explanationHi: "काली मिट्टी को आमतौर पर रेगुर (या काली कपास मिट्टी) के रूप में जाना जाता है और यह खनिजों और मिट्टी के अंश से समृद्ध होती है।",
    difficulty: "EASY",
    isPYQ: true,
    pyqYear: 2020,
  },
  {
    id: "q-uuid-geo-t3-3",
    topicId: "topic-uuid-static-geo-t3",
    text: "Tropical Evergreen forests in India are found in regions receiving an annual rainfall of more than:",
    textHi: "भारत में उष्णकटिबंधीय सदाबहार वन उन क्षेत्रों में पाए जाते हैं जहाँ वार्षिक वर्षा अधिक होती है:",
    optionA: "200 cm", optionAHi: "200 सेमी से",
    optionB: "100 cm", optionBHi: "100 सेमी से",
    optionC: "70 cm", optionCHi: "70 सेमी से",
    optionD: "50 cm", optionDHi: "50 सेमी से",
    correctOption: "A",
    explanation: "Tropical evergreen forests thrive in warm and humid areas with annual precipitation exceeding 200 cm.",
    explanationHi: "उष्णकटिबंधीय सदाबहार वन गर्म और आर्द्र क्षेत्रों में पनपते हैं जहाँ वार्षिक वर्षा 200 सेमी से अधिक होती है।",
    difficulty: "MEDIUM",
    isPYQ: false,
  },
  {
    id: "q-uuid-geo-t3-4",
    topicId: "topic-uuid-static-geo-t3",
    text: "The red color of red soil is primarily due to the diffusion of which element?",
    textHi: "लाल मिट्टी का लाल रंग मुख्य रूप से किस तत्व के प्रसार के कारण होता है?",
    optionA: "Iron Oxides", optionAHi: "लोहे के ऑक्साइड",
    optionB: "Magnesium", optionBHi: "मैग्नीशियम",
    optionC: "Calcium Carbonate", optionCHi: "कैल्शियम कार्बोनेट",
    optionD: "Humus", optionDHi: "ह्यूमस",
    correctOption: "A",
    explanation: "Red soil develops a reddish color due to a wide diffusion of iron oxides in crystalline and metamorphic rocks.",
    explanationHi: "लाल मिट्टी का लाल रंग क्रिस्टलीय और कायांतरित चट्टानों में लोहे के ऑक्साइड के व्यापक प्रसार के कारण विकसित होता है।",
    difficulty: "MEDIUM",
    isPYQ: false,
  },
  {
    id: "q-uuid-geo-t3-5",
    topicId: "topic-uuid-static-geo-t3",
    text: "Sundari trees, after which the Sundarbans are named, belong to which category of vegetation?",
    textHi: "सुंदरी के पेड़, जिनके नाम पर सुंदरवन का नाम रखा गया है, किस प्रकार की वनस्पति से संबंधित हैं?",
    optionA: "Mangrove Forests", optionAHi: "मैंग्रोव वन (ज्वारीय वन)",
    optionB: "Tropical Evergreen Forests", optionBHi: "उष्णकटिबंधीय सदाबहार वन",
    optionC: "Montane Forests", optionCHi: "पर्वतीय वन",
    optionD: "Thorn Forests", optionDHi: "कँटीले वन",
    correctOption: "A",
    explanation: "Sundari trees are the most prominent mangrove species found in the delta region of Ganga and Brahmaputra.",
    explanationHi: "सुंदरी के पेड़ गंगा और ब्रह्मपुत्र के डेल्टा क्षेत्र में पाई जाने वाली सबसे प्रमुख मैंग्रोव प्रजाति हैं।",
    difficulty: "EASY",
    isPYQ: true,
    pyqYear: 2012,
  },

  // === Directive Principles and Fundamental Duties (topic-uuid-static-pol-t2) ===
  {
    id: "q-uuid-pol-t2-1",
    topicId: "topic-uuid-static-pol-t2",
    text: "In which Part of the Indian Constitution are the Directive Principles of State Policy (DPSP) enshrined?",
    textHi: "भारतीय संविधान के किस भाग में राज्य के नीति निदेशक तत्व (DPSP) निहित हैं?",
    optionA: "Part IV", optionAHi: "भाग IV",
    optionB: "Part III", optionBHi: "भाग III",
    optionC: "Part IVA", optionCHi: "भाग IVA",
    optionD: "Part V", optionDHi: "भाग V",
    correctOption: "A",
    explanation: "DPSPs are listed under Part IV of the Constitution, from Article 36 to 51.",
    explanationHi: "राज्य के नीति निदेशक तत्वों को संविधान के भाग IV में अनुच्छेद 36 से 51 तक सूचीबद्ध किया गया है।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-pol-t2-2",
    topicId: "topic-uuid-static-pol-t2",
    text: "The Directive Principles of State Policy in the Indian Constitution are borrowed from the constitution of which country?",
    textHi: "भारतीय संविधान में राज्य के नीति निदेशक तत्व किस देश के संविधान से लिए गए हैं?",
    optionA: "Ireland", optionAHi: "आयरलैंड",
    optionB: "USA", optionBHi: "यूएसए",
    optionC: "USSR", optionCHi: "यूएसएसआर",
    optionD: "Australia", optionDHi: "ऑस्ट्रेलिया",
    correctOption: "A",
    explanation: "DPSPs were borrowed from the Irish Constitution of 1937, which had copied them from Spain.",
    explanationHi: "नीति निदेशक तत्व 1937 के आयरलैंड के संविधान से लिए गए थे, जिसने इन्हें स्पेन के संविधान से अपनाया था।",
    difficulty: "EASY",
    isPYQ: true,
    pyqYear: 2018,
  },
  {
    id: "q-uuid-pol-t2-3",
    topicId: "topic-uuid-static-pol-t2",
    text: "Which Article of the Constitution of India directs the State to secure a Uniform Civil Code (UCC) for its citizens?",
    textHi: "भारत के संविधान का कौन सा अनुच्छेद राज्य को अपने नागरिकों के लिए समान नागरिक संहिता (UCC) सुरक्षित करने का निर्देश देता है?",
    optionA: "Article 44", optionAHi: "अनुच्छेद 44",
    optionB: "Article 40", optionBHi: "अनुच्छेद 40",
    optionC: "Article 48", optionCHi: "अनुच्छेद 48",
    optionD: "Article 50", optionDHi: "अनुच्छेद 50",
    correctOption: "A",
    explanation: "Article 44 states that the State shall endeavor to secure for the citizens a Uniform Civil Code throughout the territory of India.",
    explanationHi: "अनुच्छेद 44 में कहा गया है कि राज्य भारत के पूरे क्षेत्र में नागरिकों के लिए एक समान नागरिक संहिता सुरक्षित करने का प्रयास करेगा।",
    difficulty: "EASY",
    isPYQ: true,
    pyqYear: 2021,
  },
  {
    id: "q-uuid-pol-t2-4",
    topicId: "topic-uuid-static-pol-t2",
    text: "Fundamental Duties were incorporated into the Indian Constitution on the recommendation of which committee?",
    textHi: "किस समिति की सिफारिश पर भारतीय संविधान में मौलिक कर्तव्यों को शामिल किया गया था?",
    optionA: "Swaran Singh Committee", optionAHi: "स्वर्ण सिंह समिति",
    optionB: "Sarkaria Commission", optionBHi: "सरकारी आयोग",
    optionC: "Balwant Rai Mehta Committee", optionCHi: "बलवंत राय मेहता समिति",
    optionD: "Verma Committee", optionDHi: "वर्मा समिति",
    correctOption: "A",
    explanation: "The Swaran Singh Committee recommended the inclusion of Fundamental Duties, which was done via the 42nd Amendment Act in 1976.",
    explanationHi: "स्वर्ण सिंह समिति ने मौलिक कर्तव्यों को शामिल करने की सिफारिश की थी, जिसे 1976 में 42वें संशोधन अधिनियम द्वारा किया गया था।",
    difficulty: "MEDIUM",
    isPYQ: true,
    pyqYear: 2016,
  },
  {
    id: "q-uuid-pol-t2-5",
    topicId: "topic-uuid-static-pol-t2",
    text: "How many Fundamental Duties are currently listed in Article 51A of the Indian Constitution?",
    textHi: "वर्तमान में भारतीय संविधान के अनुच्छेद 51A में कितने मौलिक कर्तव्य सूचीबद्ध हैं?",
    optionA: "11", optionAHi: "11",
    optionB: "10", optionBHi: "10",
    optionC: "12", optionCHi: "12",
    optionD: "9", optionDHi: "9",
    correctOption: "A",
    explanation: "Originally there were 10 duties. The 11th duty (obligation of parents/guardians to provide education opportunities) was added by the 86th Amendment in 2002.",
    explanationHi: "मूल रूप से 10 कर्तव्य थे। 11वां कर्तव्य (माता-पिता/अभिभावकों का 6-14 वर्ष के बच्चों को शिक्षा के अवसर प्रदान करने का दायित्व) 2002 में 86वें संशोधन द्वारा जोड़ा गया था।",
    difficulty: "EASY",
    isPYQ: false,
  },

  // === Union Parliament and State Legislature (topic-uuid-static-pol-t3) ===
  {
    id: "q-uuid-pol-t3-1",
    topicId: "topic-uuid-static-pol-t3",
    text: "Who is the ex-officio Chairman of the Rajya Sabha (Council of States) in India?",
    textHi: "भारत में राज्यसभा (उच्च सदन) का पदेन सभापति कौन होता है?",
    optionA: "Vice-President of India", optionAHi: "भारत के उपराष्ट्रपति",
    optionB: "President of India", optionBHi: "भारत के राष्ट्रपति",
    optionC: "Prime Minister of India", optionCHi: "भारत के प्रधानमंत्री",
    optionD: "Speaker of Lok Sabha", optionDHi: "लोकसभा अध्यक्ष",
    correctOption: "A",
    explanation: "Article 64 and Article 89(1) state that the Vice-President of India shall be the ex-officio Chairman of the Council of States.",
    explanationHi: "अनुच्छेद 64 और अनुच्छेद 89(1) में कहा गया है कि भारत के उपराष्ट्रपति राज्यसभा के पदेन सभापति होंगे।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-pol-t3-2",
    topicId: "topic-uuid-static-pol-t3",
    text: "What is the minimum age eligibility to become a member of the Lok Sabha?",
    textHi: "लोकसभा का सदस्य बनने के लिए न्यूनतम आयु योग्यता क्या है?",
    optionA: "25 years", optionAHi: "25 वर्ष",
    optionB: "30 years", optionBHi: "30 वर्ष",
    optionC: "35 years", optionCHi: "35 वर्ष",
    optionD: "21 years", optionDHi: "21 वर्ष",
    correctOption: "A",
    explanation: "According to Article 84(b) of the Constitution, the minimum age to be elected to the Lok Sabha is 25 years.",
    explanationHi: "संविधान के अनुच्छेद 84(b) के अनुसार, लोकसभा के लिए चुने जाने की न्यूनतम आयु 25 वर्ष है।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-pol-t3-3",
    topicId: "topic-uuid-static-pol-t3",
    text: "A Money Bill can be introduced only in which house of the Parliament?",
    textHi: "धन विधेयक केवल संसद के किस सदन में पेश किया जा सकता है?",
    optionA: "Lok Sabha", optionAHi: "लोकसभा",
    optionB: "Rajya Sabha", optionBHi: "राज्यसभा",
    optionC: "Either House", optionCHi: "किसी भी सदन में",
    optionD: "Joint Session of Parliament", optionDHi: "संसद का संयुक्त सत्र",
    correctOption: "A",
    explanation: "Article 109 specifies that a Money Bill cannot be introduced in the Rajya Sabha. It can only be introduced in the Lok Sabha.",
    explanationHi: "अनुच्छेद 109 निर्दिष्ट करता है कि धन विधेयक राज्यसभा में पेश नहीं किया जा सकता। इसे केवल लोकसभा में ही पेश किया जा सकता है।",
    difficulty: "EASY",
    isPYQ: true,
    pyqYear: 2021,
  },
  {
    id: "q-uuid-pol-t3-4",
    topicId: "topic-uuid-static-pol-t3",
    text: "What is the maximum constitutional gap allowed between two consecutive sessions of Parliament?",
    textHi: "संसद के दो क्रमिक सत्रों के बीच अधिकतम संवैधानिक अंतराल कितना हो सकता है?",
    optionA: "6 months", optionAHi: "6 महीने",
    optionB: "3 months", optionBHi: "3 महीने",
    optionC: "12 months", optionCHi: "12 महीने",
    optionD: "9 months", optionDHi: "9 महीने",
    correctOption: "A",
    explanation: "Article 85 mandates that six months shall not intervene between the last sitting in one session and the date appointed for the first sitting in the next session.",
    explanationHi: "अनुच्छेद 85 निर्देश देता है कि एक सत्र की अंतिम बैठक और अगले सत्र की पहली बैठक के बीच छह महीने से अधिक का अंतर नहीं होना चाहिए।",
    difficulty: "MEDIUM",
    isPYQ: true,
    pyqYear: 2012,
  },
  {
    id: "q-uuid-pol-t3-5",
    topicId: "topic-uuid-static-pol-t3",
    text: "Who has the power to dissolve the Lok Sabha before its five-year term expires?",
    textHi: "लोकसभा का पांच वर्ष का कार्यकाल समाप्त होने से पहले उसे भंग करने की शक्ति किसके पास है?",
    optionA: "President of India on the advice of the Prime Minister", optionAHi: "प्रधानमंत्री की सलाह पर भारत के राष्ट्रपति",
    optionB: "Prime Minister of India", optionBHi: "भारत के प्रधानमंत्री",
    optionC: "Speaker of Lok Sabha", optionCHi: "लोकसभा अध्यक्ष",
    optionD: "Chief Justice of India", optionDHi: "भारत के मुख्य न्यायाधीश",
    correctOption: "A",
    explanation: "The President can dissolve the Lok Sabha before the end of its normal term on the recommendation of the Cabinet/Prime Minister.",
    explanationHi: "राष्ट्रपति कैबिनेट/प्रधानमंत्री की सिफारिश पर सामान्य कार्यकाल समाप्त होने से पहले लोकसभा को भंग कर सकते हैं।",
    difficulty: "MEDIUM",
    isPYQ: false,
  },

  // === Uttarakhand Current Affairs (topic-uuid-static-ca-t2) ===
  {
    id: "q-uuid-ca-t2-1",
    topicId: "topic-uuid-static-ca-t2",
    text: "In February 2024, Uttarakhand became the first state in independent India to pass a Bill on which subject?",
    textHi: "फरवरी 2024 में, उत्तराखंड स्वतंत्र भारत में किस विषय पर विधेयक पारित करने वाला पहला राज्य बना?",
    optionA: "Uniform Civil Code", optionAHi: "समान नागरिक संहिता",
    optionB: "Right to Education", optionBHi: "शिक्षा का अधिकार",
    optionC: "Anti-Cheating Bill", optionCHi: "नकल विरोधी विधेयक",
    optionD: "Land Reforms", optionDHi: "भूमि सुधार",
    correctOption: "A",
    explanation: "The Legislative Assembly of Uttarakhand passed the Uniform Civil Code (UCC) Bill on February 7, 2024, making it the first state in independent India to do so.",
    explanationHi: "उत्तराखंड विधानसभा ने 7 फरवरी 2024 को समान नागरिक संहिता (UCC) विधेयक पारित किया, जिससे यह स्वतंत्र भारत में ऐसा करने वाला पहला राज्य बना।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-ca-t2-2",
    topicId: "topic-uuid-static-ca-t2",
    text: "Which tunnel in Uttarakhand was the focus of a major national rescue operation in late 2023 for trapped construction workers?",
    textHi: "2023 के अंत में उत्तराखंड की कौन सी सुरंग फंसे हुए निर्माण श्रमिकों के लिए एक बड़े राष्ट्रीय बचाव अभियान का केंद्र थी?",
    optionA: "Silkyara-Barkot Tunnel", optionAHi: "सिल्क्यारा-बारकोट सुरंग",
    optionB: "Atal Tunnel", optionBHi: "अटल सुरंग",
    optionC: "Banihal Qazigund Tunnel", optionCHi: "बनिहाल काजीगुंड सुरंग",
    optionD: "Jawahar Tunnel", optionDHi: "जवाहर सुरंग",
    correctOption: "A",
    explanation: "The Silkyara-Barkot tunnel in Uttarkashi collapsed on November 12, 2023, and all 41 trapped workers were successfully rescued after 17 days on November 28, 2023.",
    explanationHi: "उत्तरकाशी में सिल्क्यारा-बारकोट सुरंग 12 नवंबर 2023 को ढह गई थी, और फंसे हुए सभी 41 श्रमिकों को 17 दिनों के बाद 28 नवंबर 2023 को सफलतापूर्वक बचा लिया गया था।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-ca-t2-3",
    topicId: "topic-uuid-static-ca-t2",
    text: "The under-construction Lakhwar Multipurpose Project, recently in the news, is being built on which river in Uttarakhand?",
    textHi: "हाल ही में चर्चा में रही निर्माणाधीन लखवाड़ बहुउद्देशीय परियोजना उत्तराखंड में किस नदी पर बनाई जा रही है?",
    optionA: "Yamuna River", optionAHi: "यमुना नदी",
    optionB: "Ganga River", optionBHi: "गंगा नदी",
    optionC: "Alaknanda River", optionCHi: "अलकनंदा नदी",
    optionD: "Kali River", optionDHi: "काली नदी",
    correctOption: "A",
    explanation: "The Lakhwar project is a 300 MW hydroelectric project with storage, under construction on the Yamuna river near Dehradun.",
    explanationHi: "लखवाड़ परियोजना देहरादून के पास यमुना नदी पर निर्माणाधीन 300 मेगावाट की जलविद्युत परियोजना है।",
    difficulty: "MEDIUM",
    isPYQ: false,
  },
  {
    id: "q-uuid-ca-t2-4",
    topicId: "topic-uuid-static-ca-t2",
    text: "Which airport in Uttarakhand is currently being expanded to serve as a major domestic and future international hub?",
    textHi: "उत्तराखंड के किस हवाई अड्डे का वर्तमान में विस्तार किया जा रहा है ताकि इसे एक प्रमुख घरेलू और भविष्य के अंतर्राष्ट्रीय केंद्र के रूप में विकसित किया जा सके?",
    optionA: "Jolly Grant Airport, Dehradun", optionAHi: "जॉली ग्रांट एयरपोर्ट, देहरादून",
    optionB: "Pantnagar Airport", optionBHi: "पंतनगर एयरपोर्ट",
    optionC: "Naini Saini Airport, Pithoragarh", optionCHi: "नैनी सैनी एयरपोर्ट, पिथौरागढ़",
    optionD: "Gauchar Airport", optionDHi: "गौचर एयरपोर्ट",
    correctOption: "A",
    explanation: "Jolly Grant Airport in Dehradun is undergoing major terminal expansion to support increased domestic and charter flights.",
    explanationHi: "घरेलू और चार्टर उड़ानों को सहारा देने के लिए देहरादून में जॉली ग्रांट हवाई अड्डे का बड़े पैमाने पर टर्मिनल विस्तार किया जा रहा है।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-ca-t2-5",
    topicId: "topic-uuid-static-ca-t2",
    text: "The state tree of Uttarakhand, Buransh, scientificially known as Rhododendron arboreum, is famous for its vibrant flowers of which color?",
    textHi: "उत्तराखंड का राज्य वृक्ष बुरांश (रोडोडेंड्रोन आर्बोरियम) किस रंग के अपने जीवंत फूलों के लिए प्रसिद्ध है?",
    optionA: "Crimson Red", optionAHi: "गहरा लाल (चटक लाल)",
    optionB: "Bright Yellow", optionBHi: "चमकीला पीला",
    optionC: "Pure White", optionCHi: "सफेद",
    optionD: "Deep Blue", optionDHi: "नीला",
    correctOption: "A",
    explanation: "Buransh flowers are famous for their dark crimson red color. They bloom during spring and are used to make traditional juice.",
    explanationHi: "बुरांश के फूल अपने चटक गहरे लाल रंग के लिए प्रसिद्ध हैं। ये वसंत ऋतु में खिलते हैं और इनका उपयोग जूस बनाने के लिए किया जाता है।",
    difficulty: "EASY",
    isPYQ: false,
  },

  // === Central Government Schemes (topic-uuid-static-ca-t3) ===
  {
    id: "q-uuid-ca-t3-1",
    topicId: "topic-uuid-static-ca-t3",
    text: "What is the primary objective of the 'Pradhan Mantri Jan Dhan Yojana' (PMJDY) launched in 2014?",
    textHi: "2014 में शुरू की गई 'प्रधानमंत्री जन धन योजना' (PMJDY) का प्राथमिक उद्देश्य क्या है?",
    optionA: "Financial Inclusion", optionAHi: "वित्तीय समावेशन",
    optionB: "Providing housing subsidies", optionBHi: "आवास सब्सिडी प्रदान करना",
    optionC: "Free LPG connections", optionCHi: "निःशुल्क एलपीजी कनेक्शन",
    optionD: "Providing credit to street vendors", optionDHi: "रेहड़ी-पटरी वालों को ऋण देना",
    correctOption: "A",
    explanation: "PMJDY is a national mission for financial inclusion to ensure access to financial services like savings accounts, remittances, and credit at affordable costs.",
    explanationHi: "PMJDY वित्तीय समावेशन के लिए एक राष्ट्रीय मिशन है ताकि किफायती दरों पर बचत खातों, प्रेषण और ऋण जैसी वित्तीय सेवाओं तक पहुंच सुनिश्चित की जा सके।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-ca-t3-2",
    topicId: "topic-uuid-static-ca-t3",
    text: "Under which scheme does the government provide free LPG connections to women members of BPL households?",
    textHi: "किस योजना के तहत सरकार गरीबी रेखा से नीचे (BPL) परिवारों की महिला सदस्यों को मुफ्त एलपीजी कनेक्शन प्रदान करती है?",
    optionA: "Pradhan Mantri Ujjwala Yojana", optionAHi: "प्रधानमंत्री उज्ज्वला योजना",
    optionB: "PM-KISAN Scheme", optionBHi: "पीएम-किसान योजना",
    optionC: "PM SVANidhi Scheme", optionCHi: "पीएम स्वनिधि योजना",
    optionD: "Ayushman Bharat PM-JAY", optionDHi: "आयुष्मान भारत पीएम-जेएवाई",
    correctOption: "A",
    explanation: "Pradhan Mantri Ujjwala Yojana (PMUY) was launched in May 2016 to provide clean cooking fuel to rural and deprived households.",
    explanationHi: "ग्रामीण और वंचित परिवारों को स्वच्छ रसोई ईंधन प्रदान करने के लिए मई 2016 में प्रधानमंत्री उज्ज्वला योजना (PMUY) शुरू की गई थी।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-ca-t3-3",
    topicId: "topic-uuid-static-ca-t3",
    text: "What is the maximum annual health insurance cover provided per family under the Ayushman Bharat PM-JAY scheme?",
    textHi: "आयुष्मान भारत पीएम-जेएवाई योजना के तहत प्रति परिवार प्रति वर्ष प्रदान किया जाने वाला अधिकतम स्वास्थ्य बीमा कवर कितना है?",
    optionA: "Rs. 5 Lakhs", optionAHi: "5 लाख रुपये",
    optionB: "Rs. 2 Lakhs", optionBHi: "2 लाख रुपये",
    optionC: "Rs. 10 Lakhs", optionCHi: "10 लाख रुपये",
    optionD: "Rs. 3 Lakhs", optionDHi: "3 लाख रुपये",
    correctOption: "A",
    explanation: "Ayushman Bharat PM-JAY provides health cover of Rs. 5 lakhs per family per year for secondary and tertiary care hospitalization.",
    explanationHi: "आयुष्मान भारत पीएम-जेएवाई माध्यमिक और तृतीयक देखभाल अस्पताल में भर्ती होने के लिए प्रति परिवार प्रति वर्ष 5 लाख रुपये का स्वास्थ्य कवर प्रदान करता है।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-ca-t3-4",
    topicId: "topic-uuid-static-ca-t3",
    text: "The 'PM Vishwakarma' scheme, launched in September 2023, is specifically designed to support which group of workers?",
    textHi: "सितंबर 2023 में शुरू की गई 'पीएम विश्वकर्मा' योजना विशेष रूप से किस प्रकार के श्रमिकों का समर्थन करने के लिए डिज़ाइन की गई है?",
    optionA: "Traditional artisans and craftspeople", optionAHi: "पारंपरिक कारीगर और शिल्पकार",
    optionB: "Young IT professionals", optionBHi: "युवा आईटी पेशेवर",
    optionC: "Dryland farmers", optionCHi: "शुष्क भूमि किसान",
    optionD: "Gig economy workers", optionDHi: "गिग इकॉनमी के कर्मचारी",
    correctOption: "A",
    explanation: "PM Vishwakarma provides training, toolkit incentive, and collateral-free credit support to traditional artisans like weavers, blacksmiths, potters, etc.",
    explanationHi: "पीएम विश्वकर्मा पारंपरिक कारीगरों (जैसे बुनकर, लोहार, कुम्हार आदि) को कौशल प्रशिक्षण, टूलकिट प्रोत्साहन और संपार्श्विक-मुक्त ऋण सहायता प्रदान करती है।",
    difficulty: "MEDIUM",
    isPYQ: false,
  },
  {
    id: "q-uuid-ca-t3-5",
    topicId: "topic-uuid-static-ca-t3",
    text: "Which national mission has a target to provide functional household tap connections (FHTC) to every rural home in India?",
    textHi: "किस राष्ट्रीय मिशन का लक्ष्य भारत के प्रत्येक ग्रामीण घर में कार्यात्मक घरेलू नल कनेक्शन (FHTC) प्रदान करना है?",
    optionA: "Jal Jeevan Mission", optionAHi: "जल जीवन मिशन",
    optionB: "Namami Gange Programme", optionBHi: "नमामि गंगे कार्यक्रम",
    optionC: "Swachh Bharat Mission (Gramin)", optionCHi: "स्वच्छ भारत मिशन (ग्रामीण)",
    optionD: "AMRUT Mission", optionDHi: "अमृत मिशन",
    correctOption: "A",
    explanation: "Jal Jeevan Mission, launched in August 2019, aims to assist, empower, and facilitate rural households with functional tap connections (Har Ghar Jal).",
    explanationHi: "अगस्त 2019 में शुरू किए गए जल जीवन मिशन का उद्देश्य ग्रामीण परिवारों को कार्यात्मक नल कनेक्शन (हर घर जल) प्रदान करना और सहायता देना है।",
    difficulty: "EASY",
    isPYQ: true,
    pyqYear: 2021,
  },

  // === Sandhi and Samas (topic-uuid-static-hindi-t2) ===
  {
    id: "q-uuid-hindi-t2-1",
    topicId: "topic-uuid-static-hindi-t2",
    text: "Which of the following describes the three main branches of Sandhi in Hindi grammar?",
    textHi: "निम्नलिखित में से कौन हिन्दी व्याकरण में संधि की तीन मुख्य श्रेणियों को दर्शाता है?",
    optionA: "Swar Sandhi, Vyanjan Sandhi, Visarg Sandhi", optionAHi: "स्वर संधि, व्यंजन संधि, विसर्ग संधि",
    optionB: "Tatsam, Tadbhav, Deshaj", optionBHi: "तत्सम, तद्भव, देशज",
    optionC: "Avyayibhav, Tatpurush, Dwandwa", optionCHi: "अव्ययीभाव, तत्पुरुष, द्वंद्व",
    optionD: "Kriya, Sangya, Sarvanam", optionDHi: "क्रिया, संज्ञा, सर्वनाम",
    correctOption: "A",
    explanation: "Sandhi is divided into three primary types based on the letters joining together: Swar (Vowels), Vyanjan (Consonants), and Visarg.",
    explanationHi: "जुड़ने वाले वर्णों के आधार पर संधि को तीन मुख्य भेदों में विभाजित किया जाता है: स्वर संधि, व्यंजन संधि और विसर्ग संधि।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-hindi-t2-2",
    topicId: "topic-uuid-static-hindi-t2",
    text: "Which Sandhi is present in the compound word 'Vidyalaya' (Vidya + Alaya)?",
    textHi: "'विद्यालय' (विद्या + आलय) शब्द में कौन सी संधि है?",
    optionA: "Dirgha Swar Sandhi", optionAHi: "दीर्घ स्वर संधि",
    optionB: "Guna Swar Sandhi", optionBHi: "गुण स्वर संधि",
    optionC: "Yan Swar Sandhi", optionCHi: "यण स्वर संधि",
    optionD: "Vriddhi Swar Sandhi", optionDHi: "वृद्धि स्वर संधि",
    correctOption: "A",
    explanation: "When similar vowels merge to create a long vowel (aa + aa = aa), it is Dirgha Swar Sandhi.",
    explanationHi: "जब दो समान स्वर मिलकर दीर्घ हो जाते हैं (आ + आ = आ), तो वहाँ दीर्घ स्वर संधि होती है।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-hindi-t2-3",
    topicId: "topic-uuid-static-hindi-t2",
    text: "What is the grammatical meaning of the term 'Samas'?",
    textHi: "व्याकरणिक दृष्टि से 'समास' शब्द का क्या अर्थ है?",
    optionA: "Summarization / Conciseness", optionAHi: "संक्षेप (संक्षिप्त करना)",
    optionB: "Expansion", optionBHi: "विस्तार",
    optionC: "Separation", optionCHi: "विग्रह (अलग करना)",
    optionD: "Modification", optionDHi: "परिवर्तन",
    correctOption: "A",
    explanation: "Samas literally means brief or summary; it is the compounding of multiple words into one concise word.",
    explanationHi: "समास का अर्थ 'संक्षेप' होता है। दो या दो से अधिक शब्दों को मिलाकर नया संक्षिप्त शब्द बनाने की प्रक्रिया को समास कहते हैं।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-hindi-t2-4",
    topicId: "topic-uuid-static-hindi-t2",
    text: "Which type of Samas is characterized by having both parts/words as equally important?",
    textHi: "किस प्रकार के समास में दोनों पद (पूर्वपद और उत्तरपद) समान रूप से प्रधान होते हैं?",
    optionA: "Dwandwa Samas", optionAHi: "द्वंद्व समास",
    optionB: "Avyayibhav Samas", optionBHi: "अव्ययीभाव समास",
    optionC: "Tatpurush Samas", optionCHi: "तत्पुरुष समास",
    optionD: "Bahuvrihi Samas", optionDHi: "बहुव्रीहि समास",
    correctOption: "A",
    explanation: "In Dwandwa Samas, both terms are coordinate and equally important, usually separated by 'aur' or a hyphen (e.g. Mata-Pita).",
    explanationHi: "द्वंद्व समास में दोनों पद प्रधान होते हैं, और इनके विग्रह में 'और' या 'या' लगता है (जैसे माता-पिता, दिन-रात)।",
    difficulty: "MEDIUM",
    isPYQ: true,
    pyqYear: 2021,
  },
  {
    id: "q-uuid-hindi-t2-5",
    topicId: "topic-uuid-static-hindi-t2",
    text: "The word 'Lambodar' (having a long belly - referring to Lord Ganesha) is an example of which Samas?",
    textHi: "'लंबोदर' (लंबा है उदर जिनका अर्थात श्री गणेश) किस समास का उदाहरण है?",
    optionA: "Bahuvrihi Samas", optionAHi: "बहुव्रीहि समास",
    optionB: "Tatpurush Samas", optionBHi: "तत्पुरुष समास",
    optionC: "Dvigu Samas", optionCHi: "द्विगु समास",
    optionD: "Karmadharaya Samas", optionDHi: "कर्मधारय समास",
    correctOption: "A",
    explanation: "In Bahuvrihi Samas, neither of the combined words is dominant. Instead, they refer to a third distinct entity (Lord Ganesha).",
    explanationHi: "बहुव्रीहि समास में कोई भी पद प्रधान नहीं होता, बल्कि दोनों पद मिलकर किसी तीसरे अर्थ (यहाँ श्री गणेश) की ओर संकेत करते हैं।",
    difficulty: "MEDIUM",
    isPYQ: true,
    pyqYear: 2016,
  },

  // === Muhavare and Lokoktiyan (topic-uuid-static-hindi-t3) ===
  {
    id: "q-uuid-hindi-t3-1",
    topicId: "topic-uuid-static-hindi-t3",
    text: "What is the meaning of the proverb 'Koyale ki dalali mein hath kale'?",
    textHi: "'कोयले की दलाली में हाथ काले' कहावत का क्या अर्थ है?",
    optionA: "Association with bad work inevitably brings bad reputation", optionAHi: "बुरे काम में शामिल होने से बदनामी मिलती ही है",
    optionB: "Working in a coal mine is dirty", optionBHi: "कोयले की खदान में काम करना गंदा है",
    optionC: "Hands get black when doing coal business", optionCHi: "कोयले के व्यापार से हाथ काले हो जाते हैं",
    optionD: "Avoid doing business of coal", optionDHi: "कोयले का व्यापार नहीं करना चाहिए",
    correctOption: "A",
    explanation: "This proverb means that if you get involved in evil or corrupt deeds, you will end up with a bad reputation.",
    explanationHi: "इस कहावत का अर्थ है कि यदि आप किसी बुरे या अनैतिक कार्य में शामिल होते हैं, तो बदनामी होना तय है।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-hindi-t3-2",
    topicId: "topic-uuid-static-hindi-t3",
    text: "What is the meaning of the Hindi idiom 'Angootha dikhana'?",
    textHi: "'अंगूठा दिखाना' मुहावरे का सही अर्थ क्या है?",
    optionA: "Refusing or denying support at the last minute", optionAHi: "वक्त पर (ऐन मौके पर) साफ मना कर देना",
    optionB: "Teasing or mocking someone", optionBHi: "किसी को चिढ़ाना",
    optionC: "Showing victory", optionCHi: "जीत प्रदर्शित करना",
    optionD: "Praising someone's efforts", optionDHi: "सराहना करना",
    correctOption: "A",
    explanation: "'Angootha dikhana' means refusing help or declining a request at the exact moment it is needed.",
    explanationHi: "इस मुहावरे का अर्थ है ऐन मौके पर किसी काम को करने या सहायता देने से साफ़ मना कर देना।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-hindi-t3-3",
    topicId: "topic-uuid-static-hindi-t3",
    text: "What is the meaning of the proverb 'Ghar ki murgi dal barabar'?",
    textHi: "'घर की मुर्गी दाल बराबर' लोकोक्ति का क्या अर्थ है?",
    optionA: "Undervaluing a high-quality asset or person because of close familiarity", optionAHi: "घर की वस्तु या व्यक्ति का कोई आदर/मूल्य न होना",
    optionB: "Chicken tastes just like cooked lentils", optionBHi: "मुर्गी दाल के स्वाद जैसी लगती है",
    optionC: "Eating simple food at home to save money", optionCHi: "सादा भोजन करना",
    optionD: "Equal distribution of food items at home", optionDHi: "घर में भोजन का समान वितरण",
    correctOption: "A",
    explanation: "This proverb indicates that people tend to take local or easily accessible talents/possessions for granted, giving them low respect.",
    explanationHi: "इस लोकोक्ति का अर्थ है कि अत्यधिक परिचित होने के कारण अपने घर की मूल्यवान वस्तु या गुणी व्यक्ति को भी कम महत्व देना।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-hindi-t3-4",
    topicId: "topic-uuid-static-hindi-t3",
    text: "What does the idiom 'Apne moonh miya mitthoo banna' mean?",
    textHi: "'अपने मुँह मियाँ मिट्ठू बनना' मुहावरे का क्या अर्थ है?",
    optionA: "Praising oneself continuously", optionAHi: "अपनी प्रशंसा स्वयं करना",
    optionB: "Speaking sweet like a parrot", optionBHi: "तोते की तरह मीठी बातें करना",
    optionC: "Flattering a superior officer", optionCHi: "दूसरों की चापलूसी करना",
    optionD: "Being extremely talkative", optionDHi: "बहुत अधिक बोलना",
    correctOption: "A",
    explanation: "This idiom refers to a person who is self-aggrandizing and constantly praises their own accomplishments.",
    explanationHi: "इस मुहावरे का अर्थ है खुद ही अपनी तारीफ या बड़ाई करते रहना।",
    difficulty: "EASY",
    isPYQ: false,
  },
  {
    id: "q-uuid-hindi-t3-5",
    topicId: "topic-uuid-static-hindi-t3",
    text: "In the popular proverb 'Naach na jaane aangan tedha', what is the implied message?",
    textHi: "'नाच न जाने आँगन टेढ़ा' लोकोक्ति का निहित अर्थ क्या है?",
    optionA: "Blaming external factors/tools for one's own lack of skill", optionAHi: "अपनी अयोग्यता का दोष दूसरों या साधनों पर मढ़ना",
    optionB: "A bent courtyard is difficult to dance on", optionBHi: "टेढ़े आँगन में नाचना असंभव है",
    optionC: "Refusing to dance in front of others", optionCHi: "नाचने से मना कर देना",
    optionD: "Courtyard architecture should be straight", optionDHi: "आँगन सीधा होना चाहिए",
    correctOption: "A",
    explanation: "The proverb is used when a person is incompetent but shifts the blame to the environment, tools, or other people.",
    explanationHi: "यह लोकोक्ति तब प्रयोग की जाती है जब कोई व्यक्ति स्वयं अयोग्य हो लेकिन अपनी असफलता का दोष परिस्थितियों या साधनों पर लगाता है।",
    difficulty: "EASY",
    isPYQ: true,
    pyqYear: 2021,
  },
];

async function main() {
  console.log("\n🌱 Starting UKPSC Quiz Content Expansion seeding...\n");

  // 1. Seed new topics
  for (const topic of newTopics) {
    await prisma.topic.upsert({
      where: { id: topic.id },
      create: { ...topic },
      update: {
        title: topic.title,
        titleHi: topic.titleHi,
        content: topic.content,
        contentHi: topic.contentHi,
        estimatedMinutes: topic.estimatedMinutes,
        orderIndex: topic.orderIndex,
      },
    });
  }
  console.log(`📝 Upserted ${newTopics.length} new Topics.`);

  // 2. Seed new questions
  for (const q of newQuestions) {
    await prisma.question.upsert({
      where: { id: q.id },
      create: { ...q },
      update: {
        text: q.text,
        textHi: q.textHi,
        optionA: q.optionA,
        optionAHi: q.optionAHi,
        optionB: q.optionB,
        optionBHi: q.optionBHi,
        optionC: q.optionC,
        optionCHi: q.optionCHi,
        optionD: q.optionD,
        optionDHi: q.optionDHi,
        correctOption: q.correctOption,
        explanation: q.explanation,
        explanationHi: q.explanationHi,
        difficulty: q.difficulty,
        isPYQ: q.isPYQ,
        pyqYear: q.pyqYear,
      },
    });
  }
  console.log(`❓ Upserted ${newQuestions.length} new Questions.`);

  console.log("\n🎉 UKPSC Quiz Content Expansion completed successfully!\n");
}

main()
  .catch((e) => {
    console.error("❌ Quiz expansion seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
